version: '3.4'
services:
  ci:
    build:
      context: .
      target: ci

  cli:
    build:
      context: .
      target: cli

  symbolicator:
    build:
      context: symbolicator
      args:
        GIT_USERNAME:
        GIT_TOKEN:
    environment:
      DSYMS_LOCATION:
      APP_NAME:
    volumes:
      - ./dSYMs:/app/dSYMs
    ports:
      - "62222:3000"

  browserstack-app-automate:
    build:
      context: test/fixtures/browserstack-app
      args:
        BUILDKITE_BRANCH:
    environment:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      BROWSER_STACK_LOCAL_IDENTIFIER: ${BUILDKITE_JOB_ID:-maze-runner}

  comparison-tests:
    build:
      context: test/fixtures/comparison
      args:
        BUILDKITE_BRANCH: